window.LAB_CENAS = {
  treino: [
    {title:'1 · A garagem dos modelos',role:'LIA',text:'Bem-vindos à garagem! Haiku, Sonnet, Opus e Fable são nomes de famílias Claude. Os caminhões são uma metáfora, não uma medida real do tamanho dos modelos.',detail:'Escolha um caminhão. O desenho diferencia as famílias; não informa parâmetros, quantidade de dados ou uma nota de inteligência.',stage:'garage'},
    {title:'2 · De onde vêm os exemplos?',role:'LLM',text:'Os livros representam exemplos de texto, código e outros dados. A Anthropic descreve misturas de fontes públicas, dados de terceiros e dados gerados internamente. Isso não é toda a internet.',detail:'As fontes e os procedimentos variam entre versões. Livros, páginas e código ilustram dados de treinamento, não uma lista completa do que cada modelo recebeu.',stage:'data'},
    {title:'3 · Treinar é praticar previsões',role:'BETO',text:'Na fábrica, escondemos o final de um exemplo. O modelo tenta prever o próximo pedaço. Depois comparamos a previsão com o pedaço que estava no exemplo.',detail:'Exemplo didático: “A xícara está cheia de…” → no texto de treino, o próximo pedaço era “ café”. O alvo vem do exemplo, não de uma verdade universal sobre xícaras.',stage:'predict'},
    {title:'4 · O ajuste acontece por dentro',role:'LLM',text:'O algoritmo mede o erro e ajusta números internos, chamados parâmetros. Esse ciclo se repete com muitos exemplos. Não é guardar cada livro numa estante para procurar uma página depois.',detail:'Parâmetros são números que influenciam os cálculos do modelo. O aprendizado muda esses números. Pode haver memorização de trechos; isso não torna o modelo uma biblioteca fiel e completa.',stage:'learn'},
    {title:'5 · Aprender a ser assistente',role:'LIA',text:'Depois do treinamento inicial, há novos ajustes para seguir instruções e responder de forma mais útil. Avaliações e feedback de pessoas ou de outros modelos podem orientar esse processo.',detail:'Pré-treinamento: aprender padrões. Pós-treinamento: ajustar o comportamento como assistente. Os métodos concretos variam; nenhuma etapa elimina todos os erros.',stage:'feedback'},
    {title:'6 · A pista de avaliação',role:'BETO',text:'Antes de colocar o caminhão na estrada, avaliamos como ele se sai em tarefas. Um resultado bom num teste não significa que vai acertar qualquer pergunta.',detail:'Avaliar é medir o comportamento em tarefas e situações de teste, incluindo casos que não serviram como exemplos daquele ajuste. Resultado depende da tarefa, versão e condições da avaliação.',stage:'evaluate'},
    {title:'7 · Agora é hora de usar',role:'LLM',text:'Quando você conversa com o modelo, ele usa o que aprendeu junto ao contexto disponível. Isso é inferência. Sua mensagem não reescreve automaticamente os parâmetros a cada resposta.',detail:'TREINAMENTO: ajusta parâmetros. USO/INFERÊNCIA: calcula uma resposta com o modelo e o contexto. Buscar uma página atual, quando há ferramenta, é uma ação diferente de ter aprendido no treinamento.',stage:'use'},
    {title:'8 · O tamanho não dá certeza',role:'LIA',text:'Um caminhão maior no desenho não prova mais livros, nem resposta sempre certa. Escolha o modelo pela tarefa, pelo tempo, pelo custo e pelas evidências. Até o gigante precisa de revisão.',detail:'As famílias têm propostas e versões diferentes. O mesmo nome não garante a mesma capacidade para sempre. Confira as fontes e teste a tarefa que importa para você.',stage:'finish'}
  ],
  sdd: [
    {title:'1 · Converse antes de codificar',role:'LIA',text:'Vamos trabalhar com SDD: primeiro explicar o que deve acontecer, depois planejar o código. Envie o pedido no chat da nossa IDE de demonstração.',detail:'IDE é o programa onde você organiza e edita o projeto. Este painel é uma simulação: as pastas e os arquivos existem apenas nesta atividade.',stage:'prompt'},
    {title:'2 · Onde guardar o combinado?',role:'LLM',text:'Entendi! Primeiro vamos guardar o combinado num documento. No curso, usamos uma pasta chamada ponto specs. Qual ação cria esse lugar?',detail:'Uma pasta organiza arquivos. “.specs” é o nome escolhido pelo curso; o ponto faz parte do nome e não ativa nenhuma inteligência artificial.',stage:'folder'},
    {title:'3 · Pasta criada. Falta o documento',role:'BETO',text:'A pasta apareceu na árvore do projeto! Mas pasta vazia não explica nenhuma regra. Vamos criar um arquivo de texto para o cadastro.',detail:'“spec” é abreviação de specification: especificação. “.md” indica Markdown, um formato de texto com marcações simples, como # para um título.',stage:'file'},
    {title:'4 · Troque o vago pelo observável',role:'LLM',text:'O documento já tem contexto e tarefa. Agora precisamos dizer o que é um preço válido. Qual regra alguém consegue testar sem adivinhar?',detail:'O produto tem nome e preço em centavos. A regra combinada com Lia permite zero e recusa negativos. Escolha como registrar isso.',stage:'rule'},
    {title:'5 · Como saber que ficou pronto?',role:'LIA',text:'Registramos a regra. Agora escreva como verificar: preço negativo, zero, preço positivo e se o produto recusado ficou fora da lista.',detail:'Critérios de aceite são condições observáveis para aceitar a entrega. Um elogio como “ficou ótimo” não substitui esses critérios.',stage:'tests'},
    {title:'6 · Salvar não é carregar',role:'LLM',text:'A especificação está pronta. Antes de alterar o código, peça para eu ler esse arquivo e apresentar um plano baseado nele.',detail:'Arquivo salvo no projeto → leitura pelo agente → informação no contexto. Criar a pasta, sozinho, não garante que o agente leia ou siga o documento.',stage:'read'},
    {title:'7 · Revise o plano',role:'BETO',text:'O agente leu a especificação e propôs validar antes de salvar, testar os três valores e preservar a listagem. Confira se esse plano segue o combinado.',detail:'Plano: ler o cadastro existente; validar antes de salvar; testar -500, 0 e 1000; conferir a lista. Um plano descreve ações futuras, não resultados já obtidos.',stage:'plan'},
    {title:'8 · Compare a entrega com a spec',role:'LIA',text:'Na simulação, a alteração ficou pequena e os três casos deram o resultado esperado. Agora compare a entrega com a especificação. É ela que diz o que verificar.',detail:'Ciclo: esclarecer → especificar → ler → planejar → implementar → testar → revisar. SDD é esse modo de trabalhar; .specs/ apenas organiza os documentos.',stage:'done'}
  ]
};
